# Generated by Django 3.2.7 on 2022-04-03 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_bid_bidder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfulBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.bid')),
            ],
        ),
    ]
